[package]
name = "irisia_macros"
version = "1.0.0"
edition = "2024"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { workspace = true, features = [
    "full",
    "extra-traits",
    "visit",
    "visit-mut",
] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
case = { workspace = true }
attr-parser-fn = { workspace = true }
darling = { workspace = true }

[features]
default = ["macro-dep-guessing"]
macro-dep-guessing = []
