[package]
name = "irisia_widgets"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irisia = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
lazy_static = { workspace = true }
taffy = { workspace = true }
