[package]
name = "tests"
version = "0.0.0"
edition = "2024"
publish = false

[dev-dependencies]
# irisia_widgets = { path = "../irisia-widgets" }
irisia = { path = "../irisia" }
irisia_backend = { path = "../irisia-backend" }
irisia_macros = { path = "../irisia-macros" }
irisia_utils = { path = "../irisia-utils" }
