[package]
name = "irisia"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
take_mut = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true, features = [
    "sync",
    "time",
    "macros",
    "rt-multi-thread",
] }
irisia_macros = { workspace = true }
irisia_backend = { workspace = true, features = ["fps_recorder"] }
irisia_utils = { workspace = true }
impl_variadics = { workspace = true }
stack_box = { workspace = true }
irisia-log = { version = "0.1.0", path = "../irisia-log" }
thiserror.workspace = true

[features]
dhat_heap = ["irisia_backend/dhat_heap"]
